### ISSUE TITLE
:root

### ISSUE THREAD

**Issue by hougasian** [ritterim/pui-website#125]
## 🔧 Enhancement Request 

Document what we're sending to :root

## Who is asking for the feature?

@hougasian

**Comment by tedk13** [comment]
I started this but I think we should clean up the `:root.scss` file in platform-ui. There are some vars that we have listed but we don't use in the platform. 

- [ ] `--duration`
- [ ] `--transitions` (The same as duration)
- [ ] `--opacity`
- [ ] `breakpoints`
- [ ] `--small` (Image size)
- [ ] `--medium` (Image size)
- [ ] `--large` (Image size)

**Comment by hougasian** [comment]
I leverage `--transitions` in the Platform and codepen. That's all I would keep. 
Breakpoints would be great if you could... 😢 
```
@media only screen and (max-width: var(--phone))
```

**Comment by tedk13** [comment]
I dream of a day when you can do this. And although we may not reference the css vars in PUI we still can keep them here knowing you _could_ use them. But as far as the breakpoints... they should probably go.

**Comment by mrtrimble** [comment]
I say get rid of 'em!

**Comment by tedk13** [comment]
@hougasian we probably don't need both `--transition` and `--duration`.  I say we get rid of `--duration`

**Comment by hougasian** [comment]
IOW, `transition` is the only thing on the list we're keeping.

**Comment by chelsealundy** [comment]
@tedk13  do you know if there is any QA work here or is FE testing it?

**Comment by Boltz23** [comment]
Closing this issue based on Ted's comment on no QA testing required.
