### ISSUE TITLE
proper hosting for new platformUI website

### ISSUE THREAD

**Issue by hougasian** [ritterim/pui-website#135]
### Azure static site hosting for platform-ui.com
- Dev: pui.rimdev.io 👈 only part we need right now
~~- Staging: pui-staging.rimdev.io~~ - as of 5/4/2022, we decided we don't need a staging environment
- Production: platformui.com

## Who is asking for the feature?

@hougasian

**Comment by Ritter-Ashley** [comment]
@hougasian created the static web app in Azure this morning.

I checked with Kraig shortly after, and these are the domains that we own:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/80332746/164239917-657caea9-2eb3-46db-8685-0f448c8ff414.png)

I added the platformui.com site to Cloudflare a few minutes ago and the DNS is propagating. Kraig authorized the DNS servers, eric and maria. Once DNS provisioning is complete, I'll be able to add then app's TXT record, then set the CNAME.

We'll then need to add the yml file to GitHub actions and complete the site deployment, which is coming from the release branch.

**Comment by Ritter-Ashley** [comment]
See this [Teams discussion](https://teams.microsoft.com/l/message/19:whYnwuXkVLRTJvZ9GoBmU__wxw2tLBY0v5Sv42ca2rM1@thread.tacv2/1650471493437?tenantId=ed322795-5459-4b75-8e4c-f7018552c33a&groupId=8049d8e7-0d6e-439e-84c7-6eaf7786f58e&parentMessageId=1650471493437&teamName=DevOps&channelName=General&createdTime=1650471493437) for additional conversation details.

**Comment by Ritter-Ashley** [comment]
http://platformui.com, https://platformui.com, http://www.platformui.com and https://www.platformui.com are live and password protected. I'll talk to Kraig about he `platform-ui` iterations.

**Comment by Ritter-Ashley** [comment]
I put in a ticket for the `platform-ui` side of things.

**Comment by Ritter-Ashley** [comment]
@hougasian Kraig completed the `platform-ui` side of things.

I'll document the process for how we did all of this.
