### ISSUE TITLE
Continuous loop for rocket ship animation on landing page

### ISSUE THREAD

**Issue by Azbury** [ritterim/pui-website#142]
## 🔧 Enhancement Request 

Put the rocket ship and stars animation on a continuous loop on the landing page

## Who is asking for the feature?

@Azbury 

## What business problem is this hoping to solve?

Prove once and for all that RIMdev is not to be messed with

**Comment by mrtrimble** [comment]
@tedk13 took care of this one!

**Comment by tedk13** [comment]
I did the easy part.

**Comment by mackenziegates** [comment]
can we get an estimate on this?
