### ISSUE TITLE
Update PUI Website to ver 1.4.0

### ISSUE THREAD

**Issue by mrtrimble** [ritterim/pui-website#144]
## 🔧 Enhancement Request 
Once Platform UI ver. 1.4.0. is published to npm, updates to the Platform UI Website will need to occur as there have been changes to utility classes. 

Following changes will need to occur:
- [x]  `text-{color}` change to `text--{color}` - Text color utility classes BEM syntax change, all instances on the site
- [x]  `text-{color}--hover` change to `text-hover--{color}` - Text Hover color utility classes BEM syntax change, all instances on the site
- [x]  `background-{color}` change to `background--{color}` - Background color utility classes BEM syntax change, all instances on the site
- [x]  `background-{color}—hover` change to `background-hover--{color}` - Background Hover utility classes BEM syntax change, all instances on the site
- [x] Text Size Utilities
  - Check pages and adjust sizes for new typography scale 
- [x] Documentation for all above items will need to be updated
  - Text color
  - Text Hover color
  - Background color
  - Background Hover color
  - Text size utilities
- [x] Update display utility classes (remove depricated classes) 

## Who is asking for the feature?
Frontend

## What business problem is this hoping to solve?
Keep Platform UI site up-to-date with the latest version of Platform UI

## Estimate
FE - 1

**Comment by mackenziegates** [comment]
Could you please add an estimate to this issue?

**Comment by tedk13** [comment]
Looks like it's set to 1. I can't see when it was added though. But, for the record, that's what I would have given it. @mrtrimble you agree?
