### ISSUE TITLE
Visualizer

### ISSUE THREAD

**Issue by hougasian** [ritterim/pui-website#163]
## 🔧 Enhancement Request 

Create visualizers for the following:

### utility 

- [x] backgrounds 
- [x] borders
- [x] loader
- [x] position
- [x] rotate
- [ ] scale-hover
- [ ] shadow hover
- [x] truncate with ellipsis

### Components

- [x] Buttons
- [x] messages
- [ ] pills

### Flex layout

- [x]  this

## Who is asking for the feature?

FE

**Comment by mrtrimble** [comment]
closing!

**Comment by mackenziegates** [comment]
@mrtrimble  can you please add an estimate to this issue?
