### ISSUE TITLE
Optimize SEO

### ISSUE THREAD

**Issue by eridolfi12** [ritterim/pui-website#256]
## 🔧 Enhancement Request 

Optimize SEO

## Who is asking for the feature?
Frontend

## What business problem is this hoping to solve?
Provide additional exposure to Platform UI site.

**Comment by hougasian** [comment]
- [ ] optimize/test OG data
- [ ] optimize/test twitter card
- [ ] leverage [rich snippets](https://developers.google.com/search/docs/appearance/structured-data/product#json-ld) with JSON-LD and front-matter

@tedk13 @mrtrimble @Azbury @jaime-lynn any additional thoughts for increasing our SEO?

**Comment by mrtrimble** [comment]
Polypane is helpful for twitter/open graph stuff:

<img width="2032" alt="Screen Shot 2022-10-26 at 2 43 18 PM" src="https://user-images.githubusercontent.com/5217768/198109884-13557506-af85-4c17-a62c-2a8367260003.png">

**Comment by tedk13** [comment]
I'd recommend at least running a lighthouse test to see what they recommend for improving SEO as well.
