### ISSUE TITLE
Convert pui-website to Astro

### ISSUE THREAD

**Issue by hougasian** [ritterim/pui-website#291]
## 🔧 Enhancement Request 

Keeping in line with our current refactors; migrate to Astro/Vite from Hugo.

## Who is asking for the feature?

@hougasian 

## What business problem is this hoping to solve?

Migrating away from Hugo.

## Estimates
FE - 5
QA - 1

**Comment by jjwalck** [comment]
Verified in dev. I went through https://pui.rimdev.io/, per teds instructions, clicking through each section of `Docs`, `Icons`, and `Launchpad` looking for 404 pages. All pages load properly without error.
