### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by tedk13** [ritterim/pui-website#31]
## 🔧 Enhancement Request 

- [ ] Possibly change the focus outline and switch to box-shadow
- [x] Remove Ritter terminology - Post section

## Who is asking for the feature?

Platform UI Team

## What business problem is this hoping to solve?

Improved documentation of styleguide.

**Comment by tedk13** [comment]
I'm not even sure what this is for? Pui-website buttons or platform UI buttons?

**Comment by hougasian** [comment]
is there a benefit to using box-shadow? using outline on focus also handles browser imposed `:focus` issues. 
Leaving closed unless @tedk13 wants to re-open.

**Comment by tedk13** [comment]
I wish I remember why I created this issue. Let's just leave it closed.
