### ISSUE TITLE
Z Index Issue 

### ISSUE THREAD

**Issue by chelsealundy** [ritterim/pui-website#328]
## 🐛 Bug Report

I found a little Z Index issue. 

## To Reproduce

1. Go to https://platformui.com/docs/utilities/z-index/#using-data-attributes
2. Scroll Down 

## Expected behavior

The 999 should not appear in the header. 

## Screenshots and/or request snippets

![image](https://github.com/ritterim/platform-ui/assets/13785287/d49045b3-b396-4506-a6b3-cf03ab673ebf)

## Estimates

FE & QA - 0.5

**Comment by Boltz23** [comment]
I tested this and the Header no longer has the "999" there when you scroll down. I tested other dropdowns and other pages they look good. I will attach a screenshot and close. 

<img width="949" alt="2024-01-24 14_58_08-Z-Index _ Platform UI  A CSS framework by RIMdev" src="https://github.com/ritterim/pui-website/assets/101264042/085dd07b-dd27-4ea4-b04f-8acce8b1cbbf">
